title: Fauzan Ghazi # your name (or website title) here
logo: "/images/Fauzan.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Language Teacher wo loves data viz
  <br><br>
  INFJ. SQL. Tableau. 
  <br><br>
  <a href="https://www.linkedin.com/in/fauzan-ghazi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
